def total_revenue_in_region(sales_data: list, region: str) -> int:
    """Sum of revenue for the specified region."""
    
    
    return sum(record['revenue'] for record in sales_data if record['region'] == region)
    

def revenue_range_for_product(sales_data: list, product: str) -> int:
    """Maximum revenue minus minimum revenue for the given product."""
    
    
    revenues = [record['revenue'] for record in sales_data if record['product'] == product]
    if not revenues:
        return 0
    return max(revenues) - min(revenues)
    

def region_with_max_sales(sales_data: list) -> str:
    """Region with highest total revenue; ties broken by total quantity_sold."""
    
    
    rev_by_region = {}
    qty_by_region = {}

    for rec in sales_data:
        if rec['region'] not in rev_by_region:
            rev_by_region[rec['region']] = 0
            qty_by_region[rec['region']] = 0
        rev_by_region[rec['region']] += rec['revenue']
        qty_by_region[rec['region']] += rec['quantity_sold']


    return max(
        rev_by_region,
        key=lambda x: (rev_by_region.get(x), qty_by_region.get(x)),
    )
    

def steady_revenue_products(sales_data: list) -> list:
    """Products whose revenue range is < 5000, sorted alphabetically."""
    
    
    from collections import defaultdict

    rev_by_product = defaultdict(list)
    for rec in sales_data:
        rev_by_product[rec['product']].append(rec['revenue'])

    return {
        prod for prod, revs in rev_by_product.items()
        if revs and (max(revs) - min(revs) < 5000)
    }
    
# Sales Records Analysis
# You are given a list of sales records, where each record is a dictionary with the following keys:

# "product" (str) - name of the product
# "region" (str) - region where the sale happened
# "revenue" (int) - revenue generated by the sale (in dollars)
# "quantity_sold" (int) - number of units sold
# Implement the following functions:

# total_revenue_in_region(sales_data: list[dict], region: str) -> int
# Returns the sum of revenue for all records whose region matches the given region. If the region does not appear in the data, return 0.
# revenue_range_for_product(sales_data: list[dict], product: str) -> int
# For the given product, compute the difference between the maximum and minimum revenue among its records.
# If the product appears only once, the range is 0. If the product does not appear at all, also return 0. If no product satisfies the condition, return an empty set.
# region_with_max_sales(sales_data: list[dict]) -> str
# Determine the region that generated the highest total revenue.
# If multiple regions tie on total revenue, pick the one with the larger total quantity_sold.
# steady_revenue_products(sales_data: list[dict]) -> set[str]
# Return a set of product names whose revenue range (as defined in function 2) is strictly less than 5000.\

